# Generated by Django 3.2.6 on 2021-09-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210909_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(default=9, null=True),
        ),
    ]
